# Generated by Django 5.0.13 on 2025-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
